/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const DeviceId = IDL.Text;
export const DeviceRole = IDL.Variant({
  'admin' : IDL.Null,
  'cashier' : IDL.Null,
  'driver' : IDL.Null,
});
export const Device = IDL.Record({
  'active' : IDL.Bool,
  'activatedAt' : IDL.Int,
  'role' : DeviceRole,
  'restaurantId' : IDL.Text,
  'deviceId' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : Device, 'err' : IDL.Text });
export const MenuItem = IDL.Record({
  'itemId' : IDL.Text,
  'name' : IDL.Text,
  'visible' : IDL.Bool,
  'category' : IDL.Text,
  'image' : IDL.Vec(IDL.Nat8),
  'price' : IDL.Nat,
  'vatRate' : IDL.Nat,
  'unitName' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text });
export const Restaurant = IDL.Record({
  'name' : IDL.Text,
  'restaurantId' : IDL.Text,
  'address' : IDL.Text,
  'visible' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : Restaurant, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'expired' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'shipping' : IDL.Null,
  'pickedUp' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'itemId' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'vatRate' : IDL.Nat,
  'unitName' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'none' : IDL.Null,
  'invoiced' : IDL.Null,
  'failed' : IDL.Null,
});
export const Order = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'cusTaxCode' : IDL.Text,
  'cusName' : IDL.Text,
  'createdAt' : IDL.Int,
  'taxTotal' : IDL.Nat,
  'ahamoveOrderId' : IDL.Text,
  'tingeeQrCode' : IDL.Text,
  'shippingFee' : IDL.Nat,
  'invoiceId' : IDL.Text,
  'sharedLink' : IDL.Text,
  'cusPhone' : IDL.Text,
  'orderId' : IDL.Text,
  'restaurantId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'bookingStatus' : BookingStatus,
  'receiverEmail' : IDL.Text,
  'pickupCode' : IDL.Text,
  'expireAt' : IDL.Opt(IDL.Nat64),
  'pdfUrl' : IDL.Text,
  'tingeeQrId' : IDL.Text,
  'goodsAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'amount' : IDL.Nat,
  'cusAddress' : IDL.Text,
  'invoiceStatus' : InvoiceStatus,
  'billId' : IDL.Opt(IDL.Text),
  'qrCode' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const RestaurantId = IDL.Text;
export const PendingActivation = IDL.Record({
  'expiresAt' : IDL.Int,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : DeviceRole,
  'used' : IDL.Bool,
  'restaurantId' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : PendingActivation,
  'err' : IDL.Text,
});
export const OrderStatus = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'tingeeQrCode' : IDL.Text,
  'invoiceId' : IDL.Text,
  'sharedLink' : IDL.Text,
  'bookingStatus' : BookingStatus,
  'pdfUrl' : IDL.Text,
  'tingeeQrId' : IDL.Text,
  'invoiceStatus' : InvoiceStatus,
});
export const Result_5 = IDL.Variant({ 'ok' : OrderStatus, 'err' : IDL.Text });
export const StoreHours = IDL.Record({
  'closeMinute' : IDL.Nat,
  'closeHour' : IDL.Nat,
  'openMinute' : IDL.Nat,
  'openHour' : IDL.Nat,
});
export const MenuEntry = IDL.Record({ 'itemId' : IDL.Text, 'menu' : MenuItem });
export const OrderId = IDL.Text;
export const OrderEntry = IDL.Record({ 'order' : Order, 'orderId' : OrderId });
export const RestaurantEntry = IDL.Record({
  'restaurantId' : IDL.Text,
  'restaurant' : Restaurant,
});
export const RestaurantMenuOverrideEntry = IDL.Record({
  'restaurantId' : IDL.Text,
  'overrides' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const DeviceEntry = IDL.Record({
  'device' : Device,
  'deviceId' : IDL.Text,
});
export const PendingActivationEntry = IDL.Record({
  'code' : IDL.Text,
  'activation' : PendingActivation,
});
export const UpgradeState = IDL.Record({
  'menus' : IDL.Vec(MenuEntry),
  'orders' : IDL.Vec(OrderEntry),
  'restaurants' : IDL.Vec(RestaurantEntry),
  'restaurantMenuOverrides' : IDL.Vec(RestaurantMenuOverrideEntry),
  'devices' : IDL.Vec(DeviceEntry),
  'pendingActivations' : IDL.Vec(PendingActivationEntry),
});
export const Email = IDL.Text;
export const SendCodeResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const Hmac = IDL.Text;
export const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_7], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'activateDevice' : IDL.Func([IDL.Text, DeviceId, IDL.Text, IDL.Text], [Result_4], []),
  'addItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Nat8),
      ],
      [Result_2],
      [],
    ),
  'addRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'cleanupExpiredActivations' : IDL.Func([], [IDL.Nat], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Result],
      [],
    ),
  'deleteItem' : IDL.Func([IDL.Text], [Result_3], []),
  'deleteRestaurant' : IDL.Func([IDL.Text], [Result_3], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'generateActivationCode' : IDL.Func(
      [RestaurantId, DeviceRole],
      [Result_6],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterIdText' : IDL.Func([], [IDL.Text], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuForRestaurant' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'getItemImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Result], []),
  'getOrderStatus' : IDL.Func([IDL.Text], [Result_5], ['query']),
  'getPaymentMode' : IDL.Func([], [IDL.Text], ['query']),
  'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getStoreHours' : IDL.Func([], [StoreHours], ['query']),
  'getUpgradeState' : IDL.Func([], [UpgradeState], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailVerified' : IDL.Func([Email], [IDL.Bool], ['query']),
  'isStoreOpen' : IDL.Func([], [IDL.Bool], ['query']),
  'listDevicesByRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'listDevicesByRole' : IDL.Func([DeviceRole], [IDL.Vec(Device)], ['query']),
  'listMenus' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getOrdersByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'listPaidOrdersForPickup' : IDL.Func([], [IDL.Vec(Order)], []),
  'listPendingPaymentOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'markPaymentExpired' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'markPickedUp' : IDL.Func([IDL.Text], [Result], []),
  'restoreUpgradeState' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
  'revokeDevice' : IDL.Func([DeviceId], [Result_4], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'seedMenuItems' : IDL.Func([], [IDL.Bool], []),
  'sendVerificationCode' : IDL.Func([Email], [SendCodeResult], []),
  'setPaymentMode' : IDL.Func([IDL.Text], [Result_3], []),
  'setRestaurantPriceOverride' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [Result_3],
      [],
    ),
  'setStoreHours' : IDL.Func([StoreHours], [Result_3], []),
  'setVpsSecret' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'snapshotUpgradeState' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'updateInvoiceStatus' : IDL.Func(
      [OrderId, InvoiceStatus, IDL.Text, IDL.Text, Hmac],
      [Result],
      [],
    ),
  'updateItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Nat8),
        IDL.Bool,
      ],
      [Result_2],
      [],
    ),
  'setItemVisible' : IDL.Func([IDL.Text, IDL.Bool], [Result_2], []),
  'updateOrderQr' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
        IDL.Text,
      ],
      [Result],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [OrderId, PaymentStatus, Hmac],
      [Result],
      [],
    ),
  'updateRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Result_1],
      [],
    ),
  'updateStatus' : IDL.Func([OrderId, BookingStatus, Hmac], [Result], []),
  'verifyEmailCode' : IDL.Func([Email, IDL.Text], [VerifyResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const DeviceId = IDL.Text;
  const DeviceRole = IDL.Variant({
    'admin' : IDL.Null,
    'cashier' : IDL.Null,
    'driver' : IDL.Null,
  });
  const Device = IDL.Record({
    'active' : IDL.Bool,
    'activatedAt' : IDL.Int,
    'role' : DeviceRole,
    'restaurantId' : IDL.Text,
    'deviceId' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : Device, 'err' : IDL.Text });
  const MenuItem = IDL.Record({
    'itemId' : IDL.Text,
    'name' : IDL.Text,
    'visible' : IDL.Bool,
    'category' : IDL.Text,
    'image' : IDL.Vec(IDL.Nat8),
    'price' : IDL.Nat,
    'vatRate' : IDL.Nat,
    'unitName' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text });
  const Restaurant = IDL.Record({
    'name' : IDL.Text,
    'restaurantId' : IDL.Text,
    'address' : IDL.Text,
    'visible' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : Restaurant, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'expired' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'shipping' : IDL.Null,
    'pickedUp' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'itemId' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'vatRate' : IDL.Nat,
    'unitName' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'none' : IDL.Null,
    'invoiced' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Order = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'cusTaxCode' : IDL.Text,
    'cusName' : IDL.Text,
    'createdAt' : IDL.Int,
    'taxTotal' : IDL.Nat,
    'ahamoveOrderId' : IDL.Text,
    'tingeeQrCode' : IDL.Text,
    'shippingFee' : IDL.Nat,
    'invoiceId' : IDL.Text,
    'sharedLink' : IDL.Text,
    'cusPhone' : IDL.Text,
    'orderId' : IDL.Text,
    'restaurantId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'bookingStatus' : BookingStatus,
    'receiverEmail' : IDL.Text,
    'pickupCode' : IDL.Text,
    'expireAt' : IDL.Opt(IDL.Nat64),
    'pdfUrl' : IDL.Text,
    'tingeeQrId' : IDL.Text,
    'goodsAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'amount' : IDL.Nat,
    'cusAddress' : IDL.Text,
    'invoiceStatus' : InvoiceStatus,
    'billId' : IDL.Opt(IDL.Text),
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const RestaurantId = IDL.Text;
  const PendingActivation = IDL.Record({
    'expiresAt' : IDL.Int,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : DeviceRole,
    'used' : IDL.Bool,
    'restaurantId' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : PendingActivation, 'err' : IDL.Text });
  const OrderStatus = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'tingeeQrCode' : IDL.Text,
    'invoiceId' : IDL.Text,
    'sharedLink' : IDL.Text,
    'bookingStatus' : BookingStatus,
    'pdfUrl' : IDL.Text,
    'tingeeQrId' : IDL.Text,
    'invoiceStatus' : InvoiceStatus,
  });
  const Result_5 = IDL.Variant({ 'ok' : OrderStatus, 'err' : IDL.Text });
  const StoreHours = IDL.Record({
    'closeMinute' : IDL.Nat,
    'closeHour' : IDL.Nat,
    'openMinute' : IDL.Nat,
    'openHour' : IDL.Nat,
  });
  const MenuEntry = IDL.Record({ 'itemId' : IDL.Text, 'menu' : MenuItem });
  const OrderId = IDL.Text;
  const OrderEntry = IDL.Record({ 'order' : Order, 'orderId' : OrderId });
  const RestaurantEntry = IDL.Record({
    'restaurantId' : IDL.Text,
    'restaurant' : Restaurant,
  });
  const RestaurantMenuOverrideEntry = IDL.Record({
    'restaurantId' : IDL.Text,
    'overrides' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const DeviceEntry = IDL.Record({ 'device' : Device, 'deviceId' : IDL.Text });
  const PendingActivationEntry = IDL.Record({
    'code' : IDL.Text,
    'activation' : PendingActivation,
  });
  const UpgradeState = IDL.Record({
    'menus' : IDL.Vec(MenuEntry),
    'orders' : IDL.Vec(OrderEntry),
    'restaurants' : IDL.Vec(RestaurantEntry),
    'restaurantMenuOverrides' : IDL.Vec(RestaurantMenuOverrideEntry),
    'devices' : IDL.Vec(DeviceEntry),
    'pendingActivations' : IDL.Vec(PendingActivationEntry),
  });
  const Email = IDL.Text;
  const SendCodeResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Hmac = IDL.Text;
  const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_7], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'activateDevice' : IDL.Func([IDL.Text, DeviceId, IDL.Text, IDL.Text], [Result_4], []),
    'addItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Nat8),
        ],
        [Result_2],
        [],
      ),
    'addRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'cleanupExpiredActivations' : IDL.Func([], [IDL.Nat], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Result],
        [],
      ),
    'deleteItem' : IDL.Func([IDL.Text], [Result_3], []),
    'deleteRestaurant' : IDL.Func([IDL.Text], [Result_3], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'generateActivationCode' : IDL.Func(
        [RestaurantId, DeviceRole],
        [Result_6],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterIdText' : IDL.Func([], [IDL.Text], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuForRestaurant' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getItemImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [Result], []),
    'getOrderStatus' : IDL.Func([IDL.Text], [Result_5], ['query']),
    'getPaymentMode' : IDL.Func([], [IDL.Text], ['query']),
    'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getStoreHours' : IDL.Func([], [StoreHours], ['query']),
    'getUpgradeState' : IDL.Func([], [UpgradeState], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailVerified' : IDL.Func([Email], [IDL.Bool], ['query']),
    'isStoreOpen' : IDL.Func([], [IDL.Bool], ['query']),
    'listDevicesByRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'listDevicesByRole' : IDL.Func([DeviceRole], [IDL.Vec(Device)], ['query']),
    'listMenus' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getOrdersByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'listPaidOrdersForPickup' : IDL.Func([], [IDL.Vec(Order)], []),
    'listPendingPaymentOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'markPaymentExpired' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'markPickedUp' : IDL.Func([IDL.Text], [Result], []),
    'restoreUpgradeState' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
    'revokeDevice' : IDL.Func([DeviceId], [Result_4], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'seedMenuItems' : IDL.Func([], [IDL.Bool], []),
    'sendVerificationCode' : IDL.Func([Email], [SendCodeResult], []),
    'setPaymentMode' : IDL.Func([IDL.Text], [Result_3], []),
    'setRestaurantPriceOverride' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [Result_3],
        [],
      ),
    'setStoreHours' : IDL.Func([StoreHours], [Result_3], []),
    'setVpsSecret' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'snapshotUpgradeState' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'updateInvoiceStatus' : IDL.Func(
        [OrderId, InvoiceStatus, IDL.Text, IDL.Text, Hmac],
        [Result],
        [],
      ),
    'updateItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Nat8),
          IDL.Bool,
        ],
        [Result_2],
        [],
      ),
    'setItemVisible' : IDL.Func([IDL.Text, IDL.Bool], [Result_2], []),
    'updateOrderQr' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
          IDL.Text,
        ],
        [Result],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [OrderId, PaymentStatus, Hmac],
        [Result],
        [],
      ),
    'updateRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Result_1],
        [],
      ),
    'updateStatus' : IDL.Func([OrderId, BookingStatus, Hmac], [Result], []),
    'verifyEmailCode' : IDL.Func([Email, IDL.Text], [VerifyResult], []),
  });
};

export const init = ({ IDL }) => { return []; };