/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'shipping' : null } |
  { 'pickedUp' : null } |
  { 'confirmed' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Device {
  'active' : boolean,
  'activatedAt' : bigint,
  'role' : DeviceRole,
  'restaurantId' : string,
  'deviceId' : string,
  'name' : string,
  'phone' : string,
}
export interface DeviceEntry { 'device' : Device, 'deviceId' : string }
export type DeviceId = string;
export type DeviceRole = { 'admin' : null } |
  { 'cashier' : null } |
  { 'driver' : null };
export type Email = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Hmac = string;
export type InvoiceStatus = { 'none' : null } |
  { 'invoiced' : null } |
  { 'failed' : null };
export interface MenuEntry { 'itemId' : string, 'menu' : MenuItem }
export interface MenuItem {
  'itemId' : string,
  'name' : string,
  'visible' : boolean,
  'category' : string,
  'image' : Uint8Array,
  'price' : bigint,
  'vatRate' : bigint,
  'unitName' : string,
}
export interface Order {
  'paymentStatus' : PaymentStatus,
  'cusTaxCode' : string,
  'cusName' : string,
  'createdAt' : bigint,
  'taxTotal' : bigint,
  'ahamoveOrderId' : string,
  'tingeeQrCode' : string,
  'shippingFee' : bigint,
  'invoiceId' : string,
  'sharedLink' : string,
  'cusPhone' : string,
  'orderId' : string,
  'restaurantId' : string,
  'updatedAt' : bigint,
  'bookingStatus' : BookingStatus,
  'receiverEmail' : string,
  'pickupCode' : string,
  'expireAt' : [] | [bigint],
  'pdfUrl' : string,
  'tingeeQrId' : string,
  'goodsAmount' : bigint,
  'items' : Array<OrderItem>,
  'amount' : bigint,
  'cusAddress' : string,
  'invoiceStatus' : InvoiceStatus,
  'billId' : [] | [string],
  'qrCode' : [] | [string],
}
export interface OrderEntry { 'order' : Order, 'orderId' : OrderId }
export type OrderId = string;
export interface OrderItem {
  'itemId' : string,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'vatRate' : bigint,
  'unitName' : string,
}
export interface OrderStatus {
  'paymentStatus' : PaymentStatus,
  'tingeeQrCode' : string,
  'invoiceId' : string,
  'sharedLink' : string,
  'bookingStatus' : BookingStatus,
  'pdfUrl' : string,
  'tingeeQrId' : string,
  'invoiceStatus' : InvoiceStatus,
}
export type PaymentStatus = { 'expired' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null };
export interface PendingActivation {
  'expiresAt' : bigint,
  'code' : string,
  'createdAt' : bigint,
  'role' : DeviceRole,
  'used' : boolean,
  'restaurantId' : string,
}
export interface PendingActivationEntry {
  'code' : string,
  'activation' : PendingActivation,
}
export interface Restaurant {
  'name' : string,
  'restaurantId' : string,
  'address' : string,
  'visible' : boolean,
  'phone' : string,
}
export interface RestaurantEntry {
  'restaurantId' : string,
  'restaurant' : Restaurant,
}
export type RestaurantId = string;
export interface RestaurantMenuOverrideEntry {
  'restaurantId' : string,
  'overrides' : Array<[string, bigint]>,
}
export type Result = { 'ok' : Order } |
  { 'err' : string };
export type Result_1 = { 'ok' : Restaurant } |
  { 'err' : string };
export type Result_2 = { 'ok' : MenuItem } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : string };
export type Result_4 = { 'ok' : Device } |
  { 'err' : string };
export type Result_5 = { 'ok' : OrderStatus } |
  { 'err' : string };
export type Result_6 = { 'ok' : PendingActivation } |
  { 'err' : string };
export type Result_Km = { 'ok' : bigint } |
  { 'err' : string };
export interface TimeSlot {
  'startHour' : bigint,
  'startMinute' : bigint,
  'durationMinutes' : bigint,
}
export interface DiscountTier { 'minOrderValue' : bigint, 'discountAmount' : bigint }
export interface Promotion {
  'code' : string,
  'name' : string,
  'startDate' : string,
  'endDate' : string,
  'daysOfWeek' : Array<boolean>,
  'timeSlots' : Array<TimeSlot>,
  'dailyOrderLimit' : bigint,
  'perCustomerDailyLimit' : bigint,
  'tiers' : Array<DiscountTier>,
  'active' : boolean,
}
export type Result_Promo = { 'ok' : Promotion } |
  { 'err' : string };
export type Result_PromoList = { 'ok' : Array<Promotion> } |
  { 'err' : string };
export interface ApplyPromotionOk { 'promotionCode' : string, 'discountAmount' : bigint }
export type Result_Apply = { 'ok' : ApplyPromotionOk } |
  { 'err' : string };
export interface Voucher {
  'code' : string,
  'programCode' : string,
  'email' : string,
  'value' : bigint,
  'startDate' : string,
  'endDate' : string,
  'used' : boolean,
  'issuedAt' : bigint,
}
export type Result_Voucher = { 'ok' : bigint } |
  { 'err' : string };
export interface RegistrationPromo {
  'code' : string,
  'name' : string,
  'startDate' : string,
  'endDate' : string,
  'voucherValue' : bigint,
  'voucherValidDays' : bigint,
  'active' : boolean,
}
export type Result_RegPromo = { 'ok' : RegistrationPromo } |
  { 'err' : string };
export type Result_RegPromoList = { 'ok' : Array<RegistrationPromo> } |
  { 'err' : string };
export interface SalesTier { 'minSales' : bigint, 'voucherValue' : bigint }
export interface SalesPromo {
  'code' : string,
  'name' : string,
  'startDate' : string,
  'endDate' : string,
  'weeklyTiers' : Array<SalesTier>,
  'monthlyTiers' : Array<SalesTier>,
  'voucherValidDays' : bigint,
  'active' : boolean,
}
export type Result_SalesPromo = { 'ok' : SalesPromo } |
  { 'err' : string };
export type Result_SalesPromoList = { 'ok' : Array<SalesPromo> } |
  { 'err' : string };
export type Result_IssueSalesBonus = { 'ok' : [] | [Voucher] } |
  { 'err' : string };
export type Result_7 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type SendCodeResult = { 'ok' : null } |
  { 'err' : string };
export interface StoreHours {
  'closeMinute' : bigint,
  'closeHour' : bigint,
  'openMinute' : bigint,
  'openHour' : bigint,
}
export interface UpgradeState {
  'menus' : Array<MenuEntry>,
  'orders' : Array<OrderEntry>,
  'restaurants' : Array<RestaurantEntry>,
  'restaurantMenuOverrides' : Array<RestaurantMenuOverrideEntry>,
  'devices' : Array<DeviceEntry>,
  'pendingActivations' : Array<PendingActivationEntry>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VerifyResult = { 'ok' : null } |
  { 'err' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_7>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'activateDevice' : ActorMethod<[string, DeviceId, string, string], Result_4>,
  'addItem' : ActorMethod<
    [string, string, bigint, string, bigint, string, Uint8Array],
    Result_2
  >,
  'addRestaurant' : ActorMethod<[string, string, string, string], Result_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[string, string], Result>,
  'changeOrderRestaurant' : ActorMethod<[string, string, string], Result>,
  'cleanupExpiredActivations' : ActorMethod<[], bigint>,
  'createOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<OrderItem>,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
    ],
    Result
  >,
  'deleteItem' : ActorMethod<[string], Result_3>,
  'deleteRestaurant' : ActorMethod<[string], Result_3>,
  'execute' : ActorMethod<[string], Result__1>,
  'generateActivationCode' : ActorMethod<[RestaurantId, DeviceRole], Result_6>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns the canister's own id as text, so the VPS knows which canister
   * / it is talking to. `Principal.fromActor(Main)` resolves the actor's own
   * / canister principal at runtime (mo:core/IC.getCanisterId does not exist in
   * / core 2.6.1).
   */
  'getCanisterIdText' : ActorMethod<[], string>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuForRestaurant' : ActorMethod<[string], Array<MenuItem>>,
  'getKmUsageCount' : ActorMethod<[string, string], bigint>,
  'createPromotion' : ActorMethod<[string, string, string, Array<boolean>, Array<TimeSlot>, bigint, bigint, Array<DiscountTier>], Result_Promo>,
  'updatePromotion' : ActorMethod<[string, string, string, string, Array<boolean>, Array<TimeSlot>, bigint, bigint, Array<DiscountTier>, boolean], Result_Promo>,
  'deletePromotion' : ActorMethod<[string], Result_3>,
  'listPromotions' : ActorMethod<[], Result_PromoList>,
  'getCurrentPromotion' : ActorMethod<[], [] | [Promotion]>,
  'applyPromotion' : ActorMethod<[string, bigint, string], Result_Apply>,
  'applyVoucher' : ActorMethod<[string, string, bigint, string], Result_Voucher>,
  'listMyVouchers' : ActorMethod<[string], Array<Voucher>>,
  'createRegistrationPromo' : ActorMethod<[string, string, string, bigint, bigint], Result_RegPromo>,
  'updateRegistrationPromo' : ActorMethod<[string, string, string, string, bigint, bigint, boolean], Result_RegPromo>,
  'deleteRegistrationPromo' : ActorMethod<[string], Result_3>,
  'listRegistrationPromos' : ActorMethod<[], Result_RegPromoList>,
  'createSalesPromo' : ActorMethod<[string, string, string, Array<SalesTier>, Array<SalesTier>, bigint], Result_SalesPromo>,
  'updateSalesPromo' : ActorMethod<[string, string, string, string, Array<SalesTier>, Array<SalesTier>, bigint, boolean], Result_SalesPromo>,
  'deleteSalesPromo' : ActorMethod<[string], Result_3>,
  'listSalesPromos' : ActorMethod<[], Result_SalesPromoList>,
  'getCurrentSalesPromo' : ActorMethod<[], [] | [SalesPromo]>,
  'issueSalesBonus' : ActorMethod<[string, string, string, bigint, string], Result_IssueSalesBonus>,
  'getItemImage' : ActorMethod<[string], [] | [Uint8Array]>,
  'getOrder' : ActorMethod<[string], Result>,
  'getOrderStatus' : ActorMethod<[string], Result_5>,
  'getPaymentMode' : ActorMethod<[], string>,
  'getRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getStoreHours' : ActorMethod<[], StoreHours>,
  'getUpgradeState' : ActorMethod<[], UpgradeState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailVerified' : ActorMethod<[Email], boolean>,
  'isStoreOpen' : ActorMethod<[], boolean>,
  'listDevicesByRestaurant' : ActorMethod<[RestaurantId], Array<Device>>,
  'listDevicesByRole' : ActorMethod<[DeviceRole], Array<Device>>,
  'listMenus' : ActorMethod<[], Array<MenuItem>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByEmail' : ActorMethod<[string], Array<Order>>,
  'listPaidOrdersForPickup' : ActorMethod<[], Array<Order>>,
  'listPendingPaymentOrders' : ActorMethod<[string], Array<Order>>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'markPaymentExpired' : ActorMethod<[string, string], Result>,
  'markPickedUp' : ActorMethod<[string], Result>,
  'restoreUpgradeState' : ActorMethod<[Uint8Array], boolean>,
  'revokeDevice' : ActorMethod<[DeviceId], Result_4>,
  'schema' : ActorMethod<[], string>,
  'seedMenuItems' : ActorMethod<[], boolean>,
  'sendVerificationCode' : ActorMethod<[Email], SendCodeResult>,
  'setPaymentMode' : ActorMethod<[string], Result_3>,
  'setRestaurantPriceOverride' : ActorMethod<
    [string, string, bigint],
    Result_3
  >,
  'setStoreHours' : ActorMethod<[StoreHours], Result_3>,
  'setVpsSecret' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'snapshotUpgradeState' : ActorMethod<[], Uint8Array>,
  'updateInvoiceStatus' : ActorMethod<
    [OrderId, InvoiceStatus, string, string, Hmac],
    Result
  >,
  'updateItem' : ActorMethod<
    [string, string, bigint, string, bigint, string, Uint8Array, boolean],
    Result_2
  >,
  'setItemVisible' : ActorMethod<[string, boolean], Result_2>,
  'updateOrderQr' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [bigint], string],
    Result
  >,
  'updatePaymentStatus' : ActorMethod<[OrderId, PaymentStatus, Hmac], Result>,
  'updateRestaurant' : ActorMethod<
    [string, string, string, string, boolean],
    Result_1
  >,
  'updateStatus' : ActorMethod<[OrderId, BookingStatus, Hmac], Result>,
  'tryConsumeKmSlot' : ActorMethod<[string, string, bigint, string], Result_Km>,
  'verifyEmailCode' : ActorMethod<[Email, string], VerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];