/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'shipping' : null } |
  { 'confirmed' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Device {
  'active' : boolean,
  'activatedAt' : bigint,
  'role' : DeviceRole,
  'restaurantId' : string,
  'deviceId' : string,
}
export interface DeviceEntry { 'device' : Device, 'deviceId' : string }
export type DeviceId = string;
export type DeviceRole = { 'admin' : null } |
  { 'cashier' : null } |
  { 'driver' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Hmac = string;
export type InvoiceStatus = { 'none' : null } |
  { 'invoiced' : null } |
  { 'failed' : null };
export interface MenuEntry { 'itemId' : string, 'menu' : MenuItem }
export interface MenuItem {
  'itemId' : string,
  'name' : string,
  'imageUrl' : string,
  'visible' : boolean,
  'category' : string,
  'price' : bigint,
  'vatRate' : bigint,
  'unitName' : string,
}
export interface Order {
  'paymentStatus' : PaymentStatus,
  'cusTaxCode' : string,
  'cusName' : string,
  'createdAt' : bigint,
  'taxTotal' : bigint,
  'ahamoveOrderId' : string,
  'shippingFee' : bigint,
  'invoiceId' : string,
  'sharedLink' : string,
  'cusPhone' : string,
  'orderId' : string,
  'restaurantId' : string,
  'updatedAt' : bigint,
  'bookingStatus' : BookingStatus,
  'receiverEmail' : string,
  'pdfUrl' : string,
  'tingeeQrId' : string,
  'goodsAmount' : bigint,
  'items' : Array<OrderItem>,
  'amount' : bigint,
  'cusAddress' : string,
  'invoiceStatus' : InvoiceStatus,
}
export interface OrderEntry { 'order' : Order, 'orderId' : OrderId }
export type OrderId = string;
export interface OrderItem {
  'itemId' : string,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'vatRate' : bigint,
  'unitName' : string,
}
export interface OrderStatus {
  'paymentStatus' : PaymentStatus,
  'invoiceId' : string,
  'sharedLink' : string,
  'bookingStatus' : BookingStatus,
  'pdfUrl' : string,
  'tingeeQrId' : string,
  'invoiceStatus' : InvoiceStatus,
}
export type PaymentStatus = { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null };
export interface PendingActivation {
  'expiresAt' : bigint,
  'code' : string,
  'createdAt' : bigint,
  'role' : DeviceRole,
  'used' : boolean,
  'restaurantId' : string,
}
export interface PendingActivationEntry {
  'code' : string,
  'activation' : PendingActivation,
}
export interface Restaurant {
  'name' : string,
  'restaurantId' : string,
  'address' : string,
  'visible' : boolean,
  'phone' : string,
}
export interface RestaurantEntry {
  'restaurantId' : string,
  'restaurant' : Restaurant,
}
export type RestaurantId = string;
export interface RestaurantMenuOverrideEntry {
  'restaurantId' : string,
  'overrides' : Array<[string, bigint]>,
}
export type Result = { 'ok' : Order } |
  { 'err' : string };
export type Result_1 = { 'ok' : Restaurant } |
  { 'err' : string };
export type Result_2 = { 'ok' : MenuItem } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : string };
export type Result_4 = { 'ok' : Device } |
  { 'err' : string };
export type Result_5 = { 'ok' : OrderStatus } |
  { 'err' : string };
export type Result_6 = { 'ok' : PendingActivation } |
  { 'err' : string };
export type Result_7 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface UpgradeState {
  'menus' : Array<MenuEntry>,
  'orders' : Array<OrderEntry>,
  'restaurants' : Array<RestaurantEntry>,
  'restaurantMenuOverrides' : Array<RestaurantMenuOverrideEntry>,
  'devices' : Array<DeviceEntry>,
  'pendingActivations' : Array<PendingActivationEntry>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_7>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'activateDevice' : ActorMethod<[string, DeviceId], Result_4>,
  'addItem' : ActorMethod<
    [string, string, bigint, string, bigint, string, string],
    Result_2
  >,
  'addRestaurant' : ActorMethod<[string, string, string, string], Result_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[string, string], Result>,
  'cleanupExpiredActivations' : ActorMethod<[], bigint>,
  'createOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<OrderItem>,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
    ],
    Result
  >,
  'deleteItem' : ActorMethod<[string], Result_3>,
  'deleteRestaurant' : ActorMethod<[string], Result_3>,
  'execute' : ActorMethod<[string], Result__1>,
  'generateActivationCode' : ActorMethod<[RestaurantId, DeviceRole], Result_6>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns the canister's own id as text, so the VPS knows which canister
   * / it is talking to. `Principal.fromActor(Main)` resolves the actor's own
   * / canister principal at runtime (mo:core/IC.getCanisterId does not exist in
   * / core 2.6.1).
   */
  'getCanisterIdText' : ActorMethod<[], string>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuForRestaurant' : ActorMethod<[string], Array<MenuItem>>,
  'getOrder' : ActorMethod<[string], Result>,
  /**
   * / Returns the canister's own id as text, so the VPS knows which canister
   * / it is talking to. `Principal.fromActor(Main)` resolves the actor's own
   * / canister principal at runtime (mo:core/IC.getCanisterId does not exist in
   * / core 2.6.1).
   */
  'getOrderStatus' : ActorMethod<[string], Result_5>,
  'getRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getUpgradeState' : ActorMethod<[], UpgradeState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDevicesByRestaurant' : ActorMethod<[RestaurantId], Array<Device>>,
  'listDevicesByRole' : ActorMethod<[DeviceRole], Array<Device>>,
  'listMenus' : ActorMethod<[], Array<MenuItem>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listPendingPaymentOrders' : ActorMethod<[string], Array<Order>>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'restoreUpgradeState' : ActorMethod<[Uint8Array], boolean>,
  'revokeDevice' : ActorMethod<[DeviceId], Result_4>,
  'schema' : ActorMethod<[], string>,
  'setRestaurantPriceOverride' : ActorMethod<
    [string, string, bigint],
    Result_3
  >,
  'setVpsSecret' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'snapshotUpgradeState' : ActorMethod<[], Uint8Array>,
  'updateInvoiceStatus' : ActorMethod<
    [OrderId, InvoiceStatus, string, string, Hmac],
    Result
  >,
  'updateItem' : ActorMethod<
    [string, string, bigint, string, bigint, string, string, boolean],
    Result_2
  >,
  'updatePaymentStatus' : ActorMethod<[OrderId, PaymentStatus, Hmac], Result>,
  'updateRestaurant' : ActorMethod<
    [string, string, string, string, boolean],
    Result_1
  >,
  'updateStatus' : ActorMethod<[OrderId, BookingStatus, Hmac], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];